In [1]:
import numpy as np

counties = [
    'Alameda', 'Alpine', 'Amador', 'Butte', 'Calaveras', 'Colusa', 'Contra Costa',
    'Del Norte', 'El Dorado', 'Fresno', 'Glenn', 'Humboldt', 'Imperial', 'Inyo',
    'Kern', 'Kings', 'Lake', 'Lassen', 'Los Angeles', 'Madera', 'Marin', 'Mariposa',
    'Mendocino', 'Merced', 'Modoc', 'Mono', 'Monterey', 'Napa', 'Nevada', 'Orange',
    'Placer', 'Plumas', 'Riverside', 'Sacramento', 'San Benito', 'San Bernardino',
    'San Diego', 'San Francisco', 'San Joaquin', 'San Luis Obispo', 'San Mateo',
    'Santa Barbara', 'Santa Clara', 'Santa Cruz', 'Shasta', 'Sierra', 'Siskiyou',
    'Solano', 'Sonoma', 'Stanislaus', 'Sutter', 'Tehama', 'Trinity', 'Tulare',
    'Tuolumne', 'Ventura', 'Yolo', 'Yuba'
]

In [2]:
print(counties)

['Alameda', 'Alpine', 'Amador', 'Butte', 'Calaveras', 'Colusa', 'Contra Costa', 'Del Norte', 'El Dorado', 'Fresno', 'Glenn', 'Humboldt', 'Imperial', 'Inyo', 'Kern', 'Kings', 'Lake', 'Lassen', 'Los Angeles', 'Madera', 'Marin', 'Mariposa', 'Mendocino', 'Merced', 'Modoc', 'Mono', 'Monterey', 'Napa', 'Nevada', 'Orange', 'Placer', 'Plumas', 'Riverside', 'Sacramento', 'San Benito', 'San Bernardino', 'San Diego', 'San Francisco', 'San Joaquin', 'San Luis Obispo', 'San Mateo', 'Santa Barbara', 'Santa Clara', 'Santa Cruz', 'Shasta', 'Sierra', 'Siskiyou', 'Solano', 'Sonoma', 'Stanislaus', 'Sutter', 'Tehama', 'Trinity', 'Tulare', 'Tuolumne', 'Ventura', 'Yolo', 'Yuba']


In [3]:
# 

impact_list = {
    'Alameda': [11335],
    'Alpine': [0], #
    'Amador': [386100],
    'Butte': [86251],
    'Calaveras': [347503],
    'Colusa': [0], #
    'Contra Costa': [21322],
    'Del Norte': [0], #
    'El Dorado': [397229208],
    'Fresno': [192405],
    'Glenn': [0], #
    'Humboldt': [254222],
    'Imperial': [0], #
    'Inyo': [103400],
    'Kern': [0], #
    'Kings': [0], #
    'Lake': [1389704],
    'Lassen': [445601],
    'Los Angeles': [0], #
    'Madera': [200650],
    'Marin': [0], #
    'Mariposa': [18670],
    'Mendocino': [739052],
    'Merced': [16470],
    'Modoc': [50200],
    'Mono': [0], #
    'Monterey': [112020],
    'Napa': [10101],
    'Nevada': [720900],
    'Orange': [0], #
    'Placer': [61636121],
    'Plumas': [2003500],
    'Riverside': [2598441],
    'Sacramento': [3200],
    'San Benito': [368564],
    'San Bernardino': [2225900],
    'San Diego': [1508303],
    'San Francisco': [0], #
    'San Joaquin': [22099],
    'San Luis Obispo': [9606],
    'San Mateo': [3000],
    'Santa Barbara': [0], #
    'Santa Clara': [12750],
    'Santa Cruz': [39850],
    'Shasta': [31358970],
    'Sierra': [0], #
    'Siskiyou': [408550],
    'Solano': [0], #
    'Sonoma': [443400],
    'Stanislaus': [114501],
    'Sutter': [0], #
    'Tehama': [1263355],
    'Trinity': [920000],
    'Tulare': [98750],
    'Tuolumne': [142405],
    'Ventura': [0],
    'Yolo': [124000],
    'Yuba': [2003400]
}








In [4]:
def get_average(list):
    sum = 0
    for i in list:
        #print(i)
        temp = impact_list[i]
        #print(temp)
        sum += temp[0]
    average = sum/(len(list)-1)
    return average


In [5]:
Alpine_adj = ['Alpine','El Dorado', 'Mono', 'Amador', 'Calaveras', 'Tuolumne']
Colusa_adj = ['Colusa','Glenn', 'Lake', 'Sutter', 'Yolo']
Del_Norte_adj = ['Del Norte','Siskiyou','Humboldt']
Glenn_adj = ['Glenn','Butte', 'Colusa', 'Mendocino', 'Tehama', 'Lake']
Imperial_adj = ['Imperial','Riverside', 'San Diego']
Kern_adj = ['Kern','Kings', 'Los Angeles', 'San Bernardino', 'Santa Barbara', 'Tulare', 'Ventura', 'San Luis Obispo']
Kings_adj = ['Kings','Fresno', 'Tulare','San Luis Obispo','Monterey','Kern']
Los_Angeles_adj = ['Los Angeles','Kern', 'San Bernardino', 'Santa Barbara', 'Ventura', 'Orange']
Marin_adj = ['Marin','Contra Costa', 'Sonoma', 'Solano', 'San Francisco']
Mono_adj = ['Mono','Alpine', 'Fresno', 'Inyo', 'Madera', 'Tuolumne']
Orange_adj = ['Orange','Riverside', 'San Bernardino', 'San Diego', 'Los Angeles']
San_Francisco_adj= ['San Francisco','Alameda', 'Contra Costa', 'Marin', 'San Mateo']
Santa_Barbara_adj = ['Santa Barbara','Alameda', 'Merced', 'San Benito', 'San Mateo', 'Santa Cruz', 'Stanislaus']
Sierra_list = ['Sierra','Lassen', 'Nevada', 'Plumas', 'Yuba']
Solano_list= ['Solano','Contra Costa', 'Marin', 'Napa', 'Sacramento', 'Sonoma', 'Yolo']
Sutter_list =['Sutter','Butte', 'Colusa', 'Placer', 'Sacramento', 'Yolo', 'Yuba']
Ventura_list = ['Ventura','Kern', 'Los Angeles', 'Santa Barbara']

total_adj = [Alpine_adj,Colusa_adj,Del_Norte_adj,Glenn_adj,Imperial_adj,Kern_adj,Kings_adj,Los_Angeles_adj,Marin_adj,Mono_adj,Orange_adj,San_Francisco_adj,Santa_Barbara_adj,Sierra_list,Solano_list,Sutter_list,Ventura_list]
print(len(total_adj))

17


In [6]:
for i in total_adj:
    print(i)
    temp_mean = get_average(i)
    temp_mean = int(temp_mean)
    #print(temp_mean)
    #print(i[0])
    impact_list[i[0]] = [temp_mean]
    #print(impact_list[i])


['Alpine', 'El Dorado', 'Mono', 'Amador', 'Calaveras', 'Tuolumne']
['Colusa', 'Glenn', 'Lake', 'Sutter', 'Yolo']
['Del Norte', 'Siskiyou', 'Humboldt']
['Glenn', 'Butte', 'Colusa', 'Mendocino', 'Tehama', 'Lake']
['Imperial', 'Riverside', 'San Diego']
['Kern', 'Kings', 'Los Angeles', 'San Bernardino', 'Santa Barbara', 'Tulare', 'Ventura', 'San Luis Obispo']
['Kings', 'Fresno', 'Tulare', 'San Luis Obispo', 'Monterey', 'Kern']
['Los Angeles', 'Kern', 'San Bernardino', 'Santa Barbara', 'Ventura', 'Orange']
['Marin', 'Contra Costa', 'Sonoma', 'Solano', 'San Francisco']
['Mono', 'Alpine', 'Fresno', 'Inyo', 'Madera', 'Tuolumne']
['Orange', 'Riverside', 'San Bernardino', 'San Diego', 'Los Angeles']
['San Francisco', 'Alameda', 'Contra Costa', 'Marin', 'San Mateo']
['Santa Barbara', 'Alameda', 'Merced', 'San Benito', 'San Mateo', 'Santa Cruz', 'Stanislaus']
['Sierra', 'Lassen', 'Nevada', 'Plumas', 'Yuba']
['Solano', 'Contra Costa', 'Marin', 'Napa', 'Sacramento', 'Sonoma', 'Yolo']
['Sutter', 'But

In [7]:
print(impact_list)

{'Alameda': [11335], 'Alpine': [79621043], 'Amador': [386100], 'Butte': [86251], 'Calaveras': [347503], 'Colusa': [378426], 'Contra Costa': [21322], 'Del Norte': [331386], 'El Dorado': [397229208], 'Fresno': [192405], 'Glenn': [771357], 'Humboldt': [254222], 'Imperial': [2053372], 'Inyo': [103400], 'Kern': [333465], 'Kings': [149249], 'Lake': [1389704], 'Lassen': [445601], 'Los Angeles': [511873], 'Madera': [200650], 'Marin': [116180], 'Mariposa': [18670], 'Mendocino': [739052], 'Merced': [16470], 'Modoc': [50200], 'Mono': [16051980], 'Monterey': [112020], 'Napa': [10101], 'Nevada': [720900], 'Orange': [1711129], 'Placer': [61636121], 'Plumas': [2003500], 'Riverside': [2598441], 'Sacramento': [3200], 'San Benito': [368564], 'San Bernardino': [2225900], 'San Diego': [1508303], 'San Francisco': [37959], 'San Joaquin': [22099], 'San Luis Obispo': [9606], 'San Mateo': [3000], 'Santa Barbara': [92286], 'Santa Clara': [12750], 'Santa Cruz': [39850], 'Shasta': [31358970], 'Sierra': [1293350],

In [8]:
M_values = []
for key in impact_list.keys() :
    M_values.append(impact_list[key][0])

In [9]:
print(M_values)
print(len(M_values))

[11335, 79621043, 386100, 86251, 347503, 378426, 21322, 331386, 397229208, 192405, 771357, 254222, 2053372, 103400, 333465, 149249, 1389704, 445601, 511873, 200650, 116180, 18670, 739052, 16470, 50200, 16051980, 112020, 10101, 720900, 1711129, 61636121, 2003500, 2598441, 3200, 368564, 2225900, 1508303, 37959, 22099, 9606, 3000, 92286, 12750, 39850, 31358970, 1293350, 408550, 119700, 443400, 114501, 10705233, 1263355, 920000, 98750, 142405, 312541, 124000, 2003400]
58


In [10]:
M = np.diag(M_values)

In [11]:
print(M)

[[   11335        0        0 ...        0        0        0]
 [       0 79621043        0 ...        0        0        0]
 [       0        0   386100 ...        0        0        0]
 ...
 [       0        0        0 ...   312541        0        0]
 [       0        0        0 ...        0   124000        0]
 [       0        0        0 ...        0        0  2003400]]


In [12]:
import csv
import pandas as pd

In [13]:

header = counties
data = M

data = pd.DataFrame(data, columns=header)
data.to_csv('M_matrix.csv', index=False)